using System.Globalization;
using FcaBedrock.Core.Spec;
using FcaBedrock.Spec.Toml;

namespace FcaBedrock.Discovery;

/// <summary>
/// Assembles the draft <see cref="SpecDocument"/> — the exact D-107 content inventory and
/// nothing else.
/// <para>
/// <b>What is deliberately absent, and why.</b> No schema or output fingerprint (a draft is a
/// starting point, never a frozen artifact — a stored hash would fossilize a schema the user has
/// not reviewed, §14); no <c>created_at</c>, tool version, path, or machine text (the no-clock
/// rule, D-079/P-13 — and a clock would break byte repeatability outright, D-112); no
/// <c>[defaults]</c>, <c>[output]</c>, templates, matchers, or <c>[binding.object_key]</c> (the
/// defaults are already correct: wide object keys are <c>row_index</c>). The caller may enrich
/// the returned record afterwards — it is a public document model — which is exactly why the
/// probe API takes no provenance parameters (P-6).
/// </para>
/// <para>
/// <b>Everything effective is authored explicitly</b>, including settings that equal their
/// defaults, so the draft documents the run that produced it rather than relying on the reader
/// to know §5.1 (D-107). Presence tracking means an omitted field is genuinely omitted: an
/// all-missing attribute writes no <c>declared_domain</c> at all, not <c>[]</c>, which the
/// resolve seam would read as "absent" anyway but which would misrepresent the observation as
/// an authored empty domain (§10.3, D-071).
/// </para>
/// </summary>
internal static class ProbeDraft
{
    /// <summary>The deterministic <c>[spec].description</c> of every probe draft (D-107/M5-IP-009).</summary>
    public const string Description = "Draft spec generated by probe.";

    /// <summary>
    /// Builds the draft from the planned attributes and their observed domains.
    /// </summary>
    public static SpecDocument Build(
        SourceReadSettings readSettings,
        ProbeOptions options,
        IReadOnlyList<DiscoveredColumn> columns,
        Func<int, RetainedDomain> domainOf,
        int truncatedCount)
    {
        var attributes = new List<AttributeSection>(columns.Count);
        foreach (var column in columns)
        {
            attributes.Add(Attribute(column, domainOf(column.Index), options.ValueRetentionLimit));
        }

        return new SpecDocument(
            Spec: new SpecSection(
                Version: 1,
                SchemaFingerprint: null,
                CxtOutputFingerprint: null,
                DatOutputFingerprint: null,
                Extends: null,
                Description: Description),
            Provenance: new ProvenanceSection(
                Author: null,
                CreatedAt: null,
                SourceUrl: null,
                SourceHash: null,
                DerivedFrom: null,
                Notes: Notes(options.ValueRetentionLimit, truncatedCount)),
            Binding: new BindingSection(
                Shape: readSettings.Shape,
                Encoding: readSettings.Encoding,
                Delimiter: readSettings.Delimiter,
                QuoteChar: readSettings.QuoteChar,
                HasHeader: readSettings.HasHeader,
                Locale: options.Locale,
                MissingToken: readSettings.MissingToken,
                // Wide authors no ordering and no role map: §5.3 gives neither to this shape,
                // and authoring one would not resolve.
                Ordering: null,
                Columns: null,
                ObjectKey: null),
            Defaults: null,
            Output: null,
            Templates: [],
            Matchers: [],
            Attributes: attributes);
    }

    /// <summary>
    /// The always-written <c>[provenance].notes</c> (D-108) — written even at zero truncations,
    /// so every draft explains which limit produced it rather than leaving a reader to guess
    /// whether a complete-looking domain is complete.
    /// </summary>
    public static string Notes(int limit, int truncatedCount) =>
        string.Create(
            CultureInfo.InvariantCulture,
            $"probe: per-attribute retention limit {limit}; truncated attributes: {truncatedCount}.");

    /// <summary>
    /// The truncation marker a truncated attribute carries in its <c>description</c> (D-108,
    /// verbatim from the §7.1 example). Human-readable by design: the strict reader rejects
    /// unknown keys, so there is no machine-readable truncation field to add (D-075).
    /// </summary>
    public static string TruncationMarker(int limit) =>
        string.Create(
            CultureInfo.InvariantCulture,
            $"probe: domain truncated after {limit} distinct values; more exist.");

    private static AttributeSection Attribute(DiscoveredColumn column, RetainedDomain domain, int limit) =>
        new(
            Name: column.Name,
            // The selector the naming matrix chose, with an EXPLICIT value_type: M5 authors no
            // typing, and `string` is the only type `identity` accepts (§10.2, D-061), but
            // writing it keeps the draft self-documenting rather than default-dependent.
            Source: column.BindByName is { } headerName
                ? new ColumnSourceSection(Index: null, Name: headerName, ValueType: SourceValueType.String)
                : new ColumnSourceSection(Index: column.Index, Name: null, ValueType: SourceValueType.String),
            Description: domain.Truncated ? TruncationMarker(limit) : null,
            Include: null,
            Template: null,
            Discretizer: new IdentityDiscretizerSection(),
            Scale: new NominalScaleSection(),
            // An all-missing attribute is real and is authored — only its domain is unknown, so
            // the domain is omitted and the Calibrate phase fills it from the data (§10.3).
            // Omitted, not `[]`: presence is information (D-071).
            DeclaredDomain: domain.Values.Count == 0 ? null : domain.Values,
            RestrictTo: null,
            ValueLabels: null,
            MissingPolicy: null,
            // The recovery half of D-108: a truncated prefix plus `include` lets a conversion of
            // this draft over the probed source re-append the tail in first-observation order
            // (§10.6/§17 rule 3), so the truncated draft and an untruncated one converge on the
            // same column set and order.
            UnknownValuePolicy: domain.Truncated ? UnknownValuePolicy.Include : null);
}
