using FcaBedrock.Core.Spec;
using FcaBedrock.Diagnostics;
using FcaBedrock.Spec.Toml;

namespace FcaBedrock.Discovery.Tests;

/// <summary>
/// The D-107 content inventory for a <b>triple</b> draft, asserted the same two ways as the wide
/// one: once as exact canonical TOML bytes, and once as a <b>negative</b> inventory naming what a
/// draft must not contain.
/// <para>
/// The triple-specific additions to the positive half are the explicitly authored
/// <c>ordering</c> and role map — a self-documenting draft must not rely on a reader knowing
/// §5.3's defaults — and predicate-kind sources carrying the exact predicate text. The negative
/// half gains one entry: <b>no <c>[binding.object_key]</c></b>, because the triple default is
/// already the subject, and authoring it would restate a default as though it were a choice.
/// </para>
/// </summary>
public sealed class ProbeTripleDraftTests
{
    private const string Csv = "s1,species,cat\ns1,colour,black\ns2,species,dog\n";

    private const string ExpectedToml =
        """
        [spec]
        version = 1
        description = "Draft spec generated by probe."

        [provenance]
        notes = "probe: per-attribute retention limit 100000; truncated attributes: 0."

        [binding]
        shape = "triple"
        encoding = "utf-8"
        delimiter = ","
        quote_char = "\""
        has_header = false
        locale = "invariant"
        missing_token = "?"
        ordering = "unordered"
        columns = { subject = 0, predicate = 1, value = 2 }

        [[attribute]]
        name = "species"
        source = { kind = "predicate", name = "species", value_type = "string" }
        declared_domain = ["cat", "dog"]
        discretizer = { kind = "identity" }
        scale = { kind = "nominal" }

        [[attribute]]
        name = "colour"
        source = { kind = "predicate", name = "colour", value_type = "string" }
        declared_domain = ["black"]
        discretizer = { kind = "identity" }
        scale = { kind = "nominal" }

        """;

    [Fact]
    public async Task ProbeTriple_WhenSuccessful_ThenWritesExactlyThisCanonicalToml()
    {
        var result = await TripleProbeFixtures.ProbeTripleCsvAsync(Csv);

        Assert.Empty(result.Diagnostics);
        Assert.Equal(ExpectedToml.ReplaceLineEndings("\n"), ProbeFixtures.Toml(result));
    }

    [Fact]
    public async Task ProbeTriple_WhenSuccessful_ThenAuthorsEveryEffectiveReadSettingExplicitly()
    {
        var settings = TripleProbeFixtures.TripleSettings(
            delimiter: '\t', hasHeader: true, missingToken: "NA", ordering: TripleOrdering.SubjectGrouped);
        var session = new FcaBedrock.Sources.TripleCsvSession(
            TripleProbeFixtures.Bytes("s\tp\tv\ns1\tspecies\tcat\n"), settings);

        var binding = ProbeFixtures.Draft(await Prober.ProbeTripleAsync(session, settings)).Binding!;

        Assert.Equal(SourceShape.Triple, binding.Shape);
        Assert.Equal("utf-8", binding.Encoding);
        Assert.Equal('\t', binding.Delimiter);
        Assert.Equal('"', binding.QuoteChar);
        Assert.True(binding.HasHeader);
        Assert.Equal("invariant", binding.Locale);
        Assert.Equal("NA", binding.MissingToken);
        Assert.Equal(TripleOrdering.SubjectGrouped, binding.Ordering);
        Assert.NotNull(binding.Columns);
    }

    [Fact]
    public async Task ProbeTriple_WhenTheLocaleIsOverridden_ThenTheDraftAuthorsIt()
    {
        // Locale is a probe OPTION, not a read setting (it is inert at M5 — probe parses no
        // numbers) but it is authored, because the draft must state every effective binding field.
        var draft = ProbeFixtures.Draft(await TripleProbeFixtures.ProbeTripleCsvAsync(
            Csv, options: ProbeOptions.Create(locale: "en-GB")));

        Assert.Equal("en-GB", draft.Binding!.Locale);
    }

    [Fact]
    public async Task ProbeTriple_WhenSuccessful_ThenAuthorsNoObjectKeySection()
    {
        // §5.4's triple default is the subject column, which is exactly what probe observed —
        // so there is nothing to author, and authoring it would be noise the user must review.
        var draft = ProbeFixtures.Draft(await TripleProbeFixtures.ProbeTripleCsvAsync(Csv));

        Assert.Null(draft.Binding!.ObjectKey);
    }

    [Fact]
    public async Task ProbeTriple_WhenSuccessful_ThenTheSpecSectionCarriesOnlyVersionAndDescription()
    {
        var spec = ProbeFixtures.Draft(await TripleProbeFixtures.ProbeTripleCsvAsync(Csv)).Spec!;

        Assert.Equal(1, spec.Version);
        Assert.Equal(ProbeDraftExpectations.Description, spec.Description);
        Assert.Null(spec.SchemaFingerprint);
        Assert.Null(spec.CxtOutputFingerprint);
        Assert.Null(spec.DatOutputFingerprint);
        Assert.Null(spec.Extends);
    }

    [Fact]
    public async Task ProbeTriple_WhenSuccessful_ThenProvenanceCarriesNotesAndNothingElse()
    {
        var provenance = ProbeFixtures.Draft(await TripleProbeFixtures.ProbeTripleCsvAsync(Csv)).Provenance!;

        Assert.Equal(ProbeDraftExpectations.NotesFor(100_000, 0), provenance.Notes);
        Assert.Null(provenance.CreatedAt);
        Assert.Null(provenance.Author);
        Assert.Null(provenance.SourceUrl);
        Assert.Null(provenance.SourceHash);
        Assert.Null(provenance.DerivedFrom);
    }

    [Fact]
    public async Task ProbeTriple_WhenSuccessful_ThenAuthorsNoDefaultsOutputTemplatesOrMatchers()
    {
        var draft = ProbeFixtures.Draft(await TripleProbeFixtures.ProbeTripleCsvAsync(Csv));

        Assert.Null(draft.Defaults);
        Assert.Null(draft.Output);
        Assert.Empty(draft.Templates);
        Assert.Empty(draft.Matchers);
    }

    [Fact]
    public async Task ProbeTriple_WhenSuccessful_ThenEachAttributeCarriesOnlyTheInventoriedFields()
    {
        var draft = ProbeFixtures.Draft(await TripleProbeFixtures.ProbeTripleCsvAsync(Csv));

        Assert.All(draft.Attributes, attribute =>
        {
            var source = Assert.IsType<PredicateSourceSection>(attribute.Source);
            Assert.Equal(SourceValueType.String, source.ValueType);
            Assert.IsType<IdentityDiscretizerSection>(attribute.Discretizer);
            Assert.IsType<NominalScaleSection>(attribute.Scale);

            Assert.Null(attribute.Include);
            Assert.Null(attribute.Template);
            Assert.Null(attribute.RestrictTo);
            Assert.Null(attribute.ValueLabels);
            Assert.Null(attribute.MissingPolicy);
            Assert.Null(attribute.Description);
            Assert.Null(attribute.UnknownValuePolicy);
        });
    }

    [Fact]
    public async Task ProbeTriple_WhenTruncated_ThenTheTomlCarriesTheMarkerIncludeAndPrefix()
    {
        // The truncated shape, pinned as bytes: description marker, retained prefix,
        // `unknown_value_policy = "include"`, and notes counting the truncation.
        const string expected =
            """
            [spec]
            version = 1
            description = "Draft spec generated by probe."

            [provenance]
            notes = "probe: per-attribute retention limit 1; truncated attributes: 1."

            [binding]
            shape = "triple"
            encoding = "utf-8"
            delimiter = ","
            quote_char = "\""
            has_header = false
            locale = "invariant"
            missing_token = "?"
            ordering = "unordered"
            columns = { subject = 0, predicate = 1, value = 2 }

            [[attribute]]
            name = "species"
            source = { kind = "predicate", name = "species", value_type = "string" }
            description = "probe: domain truncated after 1 distinct values; more exist."
            declared_domain = ["cat"]
            unknown_value_policy = "include"
            discretizer = { kind = "identity" }
            scale = { kind = "nominal" }

            """;

        var result = await TripleProbeFixtures.ProbeTripleCsvAsync(
            "s1,species,cat\ns2,species,dog\n", options: ProbeOptions.Create(valueRetentionLimit: 1));

        Assert.Equal(expected.ReplaceLineEndings("\n"), ProbeFixtures.Toml(result));
    }

    [Fact]
    public async Task ProbeTriple_WhenGivenANameMap_ThenTheTomlAuthorsNamesNotIndices()
    {
        // Addressing-mode preservation, at the byte level.
        const string csv = "subj,pred,val\ns1,species,cat\n";

        var result = await TripleProbeFixtures.ProbeTripleCsvAsync(
            csv, hasHeader: true, columns: TripleProbeFixtures.Names("subj", "pred", "val"));

        Assert.Contains(
            "columns = { subject = \"subj\", predicate = \"pred\", value = \"val\" }",
            ProbeFixtures.Toml(result),
            StringComparison.Ordinal);
    }

    // --- Repeatability -------------------------------------------------------------------------

    [Fact]
    public async Task ProbeTriple_WhenRunTwiceOverTheSameRows_ThenProducesIdenticalBytesAndDiagnostics()
    {
        // Deliberately a source that trips BOTH aggregates, so a repeated run has ordering,
        // counts, and bounded samples to disagree about.
        const string messy = "s1,\"q\"\"1\",a\ns1,\"q\"\"1\",b\ns2,ok,x\ns2,ok,y\ns2,\"q\"\"2\",z\n";
        var options = ProbeOptions.Create(valueRetentionLimit: 1);

        var first = await TripleProbeFixtures.ProbeTripleCsvAsync(messy, options: options);
        var second = await TripleProbeFixtures.ProbeTripleCsvAsync(messy, options: options);

        Assert.Equal(ProbeFixtures.Toml(first), ProbeFixtures.Toml(second));
        Assert.Equal(first.Diagnostics, second.Diagnostics);
    }

    [Fact]
    public async Task ProbeTriple_WhenDiagnosticsAreProduced_ThenTheirOrderIsFixed()
    {
        // Naming, then truncation — the same fixed order as wide, so a caller may rely on the
        // sequence rather than sorting defensively.
        const string messy = "s1,\"q\"\"1\",a\ns1,\"q\"\"1\",b\n";

        var result = await TripleProbeFixtures.ProbeTripleCsvAsync(
            messy, options: ProbeOptions.Create(valueRetentionLimit: 1));

        Assert.Equal(
            [DiagnosticCode.ProbeAttributeNameAdjusted, DiagnosticCode.ProbeDomainTruncated],
            result.Diagnostics.Select(d => d.Code));
    }

    [Fact]
    public async Task ProbeTriple_WhenNotCanceled_ThenTheTokenChangesNothing()
    {
        using var cts = new CancellationTokenSource();
        var settings = TripleProbeFixtures.TripleSettings();

        var withToken = await Prober.ProbeTripleAsync(
            TripleProbeFixtures.Fake(("s", "p", "x")), settings, null, null, cts.Token);
        var withoutToken = await Prober.ProbeTripleAsync(
            TripleProbeFixtures.Fake(("s", "p", "x")), settings);

        Assert.Equal(ProbeFixtures.Toml(withoutToken), ProbeFixtures.Toml(withToken));
    }
}
