using FcaBedrock.Core.Spec;
using FcaBedrock.Spec.Toml;

namespace FcaBedrock.Discovery.Tests;

/// <summary>
/// The D-107 content inventory, asserted twice over: once as exact canonical TOML bytes (what a
/// user actually opens), and once as a <b>negative</b> inventory naming every section and field
/// a draft must not contain.
/// <para>
/// Both directions are needed. Byte equality alone would quietly accept a new field the day
/// someone updated the expected string; the negative inventory states the rule — a probe draft
/// is a starting point, never a frozen artifact — so an added fingerprint, timestamp, or
/// <c>[defaults]</c> block fails for the reason it is wrong rather than because a literal moved.
/// </para>
/// </summary>
public sealed class ProbeDraftContentTests
{
    private const string Csv = "colour,size\nred,big\nblue,?\nred,small\n";

    // The complete draft for `Csv` under default options: every effective read setting authored
    // explicitly (even the defaulted ones), explicit value_type/discretizer/scale, and the
    // always-written provenance notes at zero truncations.
    private const string ExpectedToml =
        """
        [spec]
        version = 1
        description = "Draft spec generated by probe."

        [provenance]
        notes = "probe: per-attribute retention limit 100000; truncated attributes: 0."

        [binding]
        shape = "wide"
        encoding = "utf-8"
        delimiter = ","
        quote_char = "\""
        has_header = true
        locale = "invariant"
        missing_token = "?"

        [[attribute]]
        name = "colour"
        source = { kind = "column", name = "colour", value_type = "string" }
        declared_domain = ["red", "blue"]
        discretizer = { kind = "identity" }
        scale = { kind = "nominal" }

        [[attribute]]
        name = "size"
        source = { kind = "column", name = "size", value_type = "string" }
        declared_domain = ["big", "small"]
        discretizer = { kind = "identity" }
        scale = { kind = "nominal" }

        """;

    [Fact]
    public async Task Probe_WhenWideSourceHasUniqueHeaders_ThenWritesExactlyThisCanonicalToml()
    {
        var result = await ProbeFixtures.ProbeCsvAsync(Csv);

        Assert.Empty(result.Diagnostics);
        Assert.Equal(ExpectedToml.ReplaceLineEndings("\n"), ProbeFixtures.Toml(result));
    }

    [Fact]
    public async Task Probe_WhenSuccessful_ThenAuthorsEveryEffectiveReadSettingExplicitly()
    {
        // Authored EVEN WHEN DEFAULTED (D-107): a draft that omits a defaulted setting would
        // silently change meaning if a default ever moved, and would not be self-documenting.
        var settings = ProbeFixtures.WideSettings(delimiter: '\t', hasHeader: false, missingToken: "NA");
        var session = new FcaBedrock.Sources.WideCsvSession(ProbeFixtures.Bytes("x\ty\n"), settings);

        var binding = ProbeFixtures.Draft(await Prober.ProbeAsync(session, settings)).Binding!;

        Assert.Equal(SourceShape.Wide, binding.Shape);
        Assert.Equal("utf-8", binding.Encoding);
        Assert.Equal('\t', binding.Delimiter);
        Assert.Equal('"', binding.QuoteChar);
        Assert.False(binding.HasHeader);
        Assert.Equal("invariant", binding.Locale);
        Assert.Equal("NA", binding.MissingToken);
    }

    [Fact]
    public async Task Probe_WhenWideShape_ThenAuthorsNoOrderingRoleMapOrObjectKey()
    {
        // §5.3 gives wide neither an ordering nor a role map, and §5.4's wide default
        // (row_index) is already correct — authoring any of the three would not resolve, or
        // would restate a default as if it were a choice.
        var binding = ProbeFixtures.Draft(await ProbeFixtures.ProbeCsvAsync(Csv)).Binding!;

        Assert.Null(binding.Ordering);
        Assert.Null(binding.Columns);
        Assert.Null(binding.ObjectKey);
    }

    [Fact]
    public async Task Probe_WhenSuccessful_ThenTheSpecSectionCarriesOnlyVersionAndDescription()
    {
        var spec = ProbeFixtures.Draft(await ProbeFixtures.ProbeCsvAsync(Csv)).Spec!;

        Assert.Equal(1, spec.Version);
        Assert.Equal(ProbeDraftExpectations.Description, spec.Description);

        // No stored fingerprints: a draft is never a frozen artifact, even when its explicit
        // domains would make it fully-declared (§14). A stored hash would fossilize a schema the
        // user has not yet reviewed.
        Assert.Null(spec.SchemaFingerprint);
        Assert.Null(spec.CxtOutputFingerprint);
        Assert.Null(spec.DatOutputFingerprint);
        Assert.Null(spec.Extends);
    }

    [Fact]
    public async Task Probe_WhenSuccessful_ThenProvenanceCarriesNotesAndNothingElse()
    {
        var provenance = ProbeFixtures.Draft(await ProbeFixtures.ProbeCsvAsync(Csv)).Provenance!;

        Assert.Equal(ProbeDraftExpectations.NotesFor(100_000, 0), provenance.Notes);

        // created_at above all: reading a clock would break byte repeatability outright (D-112)
        // and violate the no-clock rule (D-079/P-13).
        Assert.Null(provenance.CreatedAt);
        Assert.Null(provenance.Author);
        Assert.Null(provenance.SourceUrl);
        Assert.Null(provenance.SourceHash);
        Assert.Null(provenance.DerivedFrom);
    }

    [Fact]
    public async Task Probe_WhenSuccessful_ThenAuthorsNoDefaultsOutputTemplatesOrMatchers()
    {
        var draft = ProbeFixtures.Draft(await ProbeFixtures.ProbeCsvAsync(Csv));

        Assert.Null(draft.Defaults);
        Assert.Null(draft.Output);
        Assert.Empty(draft.Templates);
        Assert.Empty(draft.Matchers);
    }

    [Fact]
    public async Task Probe_WhenSuccessful_ThenEachAttributeCarriesOnlyTheInventoriedFields()
    {
        var draft = ProbeFixtures.Draft(await ProbeFixtures.ProbeCsvAsync(Csv));

        Assert.All(draft.Attributes, attribute =>
        {
            // Present by contract: an explicit string value_type, identity, and nominal.
            var source = Assert.IsType<ColumnSourceSection>(attribute.Source);
            Assert.Equal(SourceValueType.String, source.ValueType);
            Assert.IsType<IdentityDiscretizerSection>(attribute.Discretizer);
            Assert.IsType<NominalScaleSection>(attribute.Scale);

            // Absent by contract. `include` and `missing_policy` are omitted rather than written
            // at their defaults: M5 authors no policy it did not decide (P-6/D-049).
            Assert.Null(attribute.Include);
            Assert.Null(attribute.Template);
            Assert.Null(attribute.RestrictTo);
            Assert.Null(attribute.ValueLabels);
            Assert.Null(attribute.MissingPolicy);
        });

        // Untruncated attributes carry neither a description marker nor an unknown-value policy.
        Assert.All(draft.Attributes, attribute =>
        {
            Assert.Null(attribute.Description);
            Assert.Null(attribute.UnknownValuePolicy);
        });
    }

    [Fact]
    public async Task Probe_WhenSuccessful_ThenAttributesFollowPhysicalSchemaOrder()
    {
        // Schema order, not observation order and not sorted: the draft's attribute order is the
        // source's column order, which is what makes a reread resolve back onto the same columns.
        var draft = ProbeFixtures.Draft(
            await ProbeFixtures.ProbeCsvAsync("zebra,apple,mango\n1,2,3\n"));

        Assert.Equal(["zebra", "apple", "mango"], draft.Attributes.Select(a => a.Name));
    }

    [Fact]
    public async Task Probe_WhenHeaderIsUnique_ThenBindsByNameNotIndex()
    {
        // A unique usable header binds by NAME, which is what preserves the reorder protection
        // wide name-binding exists for: re-running the spec against a column-reordered variant
        // still reads the same field.
        var draft = ProbeFixtures.Draft(await ProbeFixtures.ProbeCsvAsync(Csv));
        var source = (ColumnSourceSection)draft.Attributes[0].Source!;

        Assert.Equal("colour", source.Name);
        Assert.Null(source.Index);
    }

    [Fact]
    public async Task Probe_WhenSourceIsHeaderless_ThenBindsByIndexAndAuthorsHasHeaderFalse()
    {
        var settings = ProbeFixtures.WideSettings(hasHeader: false);
        var session = new FcaBedrock.Sources.WideCsvSession(ProbeFixtures.Bytes("a,b\nc,d\n"), settings);

        var draft = ProbeFixtures.Draft(await Prober.ProbeAsync(session, settings));

        Assert.False(draft.Binding!.HasHeader);
        Assert.Equal(["column_0", "column_1"], draft.Attributes.Select(a => a.Name));
        Assert.All(draft.Attributes, a =>
        {
            var source = (ColumnSourceSection)a.Source!;
            Assert.NotNull(source.Index);
            Assert.Null(source.Name);
        });
    }
}
