using System.Globalization;

namespace FcaBedrock.Discovery.Tests;

// The three settled draft strings, spelled out here INDEPENDENTLY of the
// production constants. Asserting against `ProbeDraft.Description` would only prove the code
// equals itself; these are byte contracts, so the test states the bytes.
internal static class ProbeDraftExpectations
{
    public const string Description = "Draft spec generated by probe.";

    public static string NotesFor(int limit, int truncatedAttributes) =>
        string.Create(
            CultureInfo.InvariantCulture,
            $"probe: per-attribute retention limit {limit}; truncated attributes: {truncatedAttributes}.");

    public static string MarkerFor(int limit) =>
        string.Create(
            CultureInfo.InvariantCulture,
            $"probe: domain truncated after {limit} distinct values; more exist.");
}
