using System.Collections.Immutable;
using System.Globalization;
using System.Reflection;
using System.Text.RegularExpressions;
using FcaBedrock.Core.Discretization;

namespace FcaBedrock.Core.Tests.Discretization;

/// <summary>
/// The <c>value_groups</c> group contract (§11.6, D-090/G-11): authored presence, the matcher
/// predicate, and the exact regex semantics.
/// <para>
/// Matching is asserted through <see cref="ValueGroupsDiscretizer"/>'s public
/// <c>Discretize</c> because <c>ValueGroup.Matches</c> is Core-internal — the discretizer under
/// <c>skip</c> reports a match as a bin and a non-match as an unknown, which is the same
/// matcher this file means to pin, reached through supported surface rather than reflection.
/// Expectations are hand-derived from §11.6, never generated by calling the production matcher.
/// </para>
/// </summary>
public sealed class ValueGroupTests
{
    // Asserts what the ONE group built from these arguments does with `value`, via the skip-policy
    // discretizer: Bin(label) ⇒ matched, Unknown ⇒ no group claimed it.
    private static bool Matches(string value, IReadOnlyList<string>? values, string? pattern)
    {
        var discretizer = ValueGroupsDiscretizer.Create(
            [ValueGroup.Create("G", values, pattern)], ValueGroupsUnmatched.Skip);
        return discretizer.Discretize(value).Outcome == BinOutcome.Bin;
    }

    // --- Authored presence (G-11) --------------------------------------------

    [Fact]
    public void Create_WhenValuesOmitted_ThenValuesIsNull() =>
        // null means "values was not authored" — the distinction the §14 encoding and the
        // round-trip both depend on (D-094/G-11).
        Assert.Null(ValueGroup.Create("G", values: null, pattern: "^x").Values);

    [Fact]
    public void Create_WhenValuesAuthoredEmptyAlongsideAPattern_ThenEmptyListIsRetainedNotNormalizedToNull()
    {
        // The G-11 rule that makes authored-[] and omitted byte-distinct: an authored empty list
        // survives as an EMPTY LIST, never collapsed to null.
        var group = ValueGroup.Create("G", values: [], pattern: "^x");

        Assert.NotNull(group.Values);
        Assert.Empty(group.Values);
    }

    [Fact]
    public void Create_WhenValuesAuthored_ThenAuthoredOrderAndDuplicatesAreRetained() =>
        // Authored configuration, not a canonicalized set (§14): neither sorted nor deduped.
        Assert.Equal(["b", "a", "b"], ValueGroup.Create("G", ["b", "a", "b"], pattern: null).Values);

    [Fact]
    public void Create_WhenPatternAuthored_ThenTextIsRetainedExactly() =>
        Assert.Equal("^I[0-9]{2}", ValueGroup.Create("G", null, "^I[0-9]{2}").Pattern);

    [Fact]
    public void Create_WhenPatternOmitted_ThenPatternIsNull() =>
        Assert.Null(ValueGroup.Create("G", ["a"], pattern: null).Pattern);

    [Fact]
    public void Create_WhenLabelAuthored_ThenRetainedVerbatimWithoutTrimmingOrCaseFolding() =>
        // No normalization the contract does not ask for (D-090).
        Assert.Equal(" Mixed Case ", ValueGroup.Create(" Mixed Case ", ["a"], null).Label);

    // --- The matcher-validity predicate (G-11) -------------------------------

    [Fact]
    public void Create_WhenValuesAuthoredEmptyAndNoPattern_ThenThrows() =>
        // `values = []` alone is authored-but-matches-nothing: the exact G-11 predicate is
        // (values is { Count: > 0 }) || pattern is not null, so an empty list does not qualify.
        Assert.Throws<ArgumentException>(() => ValueGroup.Create("G", values: [], pattern: null));

    [Fact]
    public void Create_WhenNeitherValuesNorPattern_ThenThrows() =>
        Assert.Throws<ArgumentException>(() => ValueGroup.Create("G", values: null, pattern: null));

    [Fact]
    public void Create_WhenValuesAuthoredEmptyWithAValidPattern_ThenValid() =>
        // The other half of the predicate: [] + a pattern IS a usable matcher.
        Assert.NotNull(ValueGroup.Create("G", values: [], pattern: "^x"));

    [Fact]
    public void Create_WhenLabelEmpty_ThenThrows() =>
        Assert.Throws<ArgumentException>(() => ValueGroup.Create(string.Empty, ["a"], null));

    [Fact]
    public void Create_WhenLabelNull_ThenThrows() =>
        Assert.Throws<ArgumentNullException>(() => ValueGroup.Create(null!, ["a"], null));

    [Fact]
    public void Create_WhenAnExplicitValueIsEmpty_ThenThrows() =>
        Assert.Throws<ArgumentException>(() => ValueGroup.Create("G", ["a", string.Empty], null));

    [Fact]
    public void Create_WhenPatternEmpty_ThenThrows() =>
        Assert.Throws<ArgumentException>(() => ValueGroup.Create("G", null, string.Empty));

    [Fact]
    public void Create_WhenPatternIsNotAValidRegex_ThenThrows() =>
        // D-090: an uncompilable pattern is one ArgumentException here (and one SpecFieldInvalid
        // at the reader) — there is deliberately no dedicated regex-error channel.
        Assert.Throws<ArgumentException>(() => ValueGroup.Create("G", null, "^I[0-9"));

    // --- Explicit-value matching ---------------------------------------------

    [Theory]
    [InlineData("HS-grad", true)]
    [InlineData("11th", true)]
    [InlineData("hs-grad", false)]   // ordinal: case matters
    [InlineData("HS-grad ", false)]  // ordinal: no trimming
    [InlineData("HS", false)]        // exact, not prefix
    [InlineData("Bachelors", false)]
    public void Discretize_WhenExplicitValues_ThenOrdinalExactEquality(string value, bool expected) =>
        Assert.Equal(expected, Matches(value, ["11th", "HS-grad"], null));

    [Fact]
    public void Discretize_WhenValuesAuthoredEmptyWithPattern_ThenOnlyThePatternMatches() =>
        // The empty list contributes no matcher; the pattern carries the group.
        Assert.True(Matches("xyz", values: [], pattern: "^x"));

    // --- Regex matching (§11.6/D-090) ----------------------------------------

    [Fact]
    public void Discretize_WhenPatternUnanchored_ThenMatchesPartially() =>
        // §11.6: partial (unanchored IsMatch) — "I[0-9]{2}" matches ANYWHERE in the value.
        Assert.True(Matches("xxI21xx", null, "I[0-9]{2}"));

    [Fact]
    public void Discretize_WhenPatternAnchored_ThenOnlyFullMatches()
    {
        Assert.True(Matches("I21", null, "^I[0-9]{2}$"));
        Assert.False(Matches("xxI21xx", null, "^I[0-9]{2}$"));
    }

    [Fact]
    public void Discretize_WhenPatternHasNoInlineOption_ThenCaseSensitiveByDefault()
    {
        Assert.True(Matches("I21", null, "^I[0-9]{2}$"));
        Assert.False(Matches("i21", null, "^I[0-9]{2}$"));
    }

    [Fact]
    public void Discretize_WhenPatternUsesInlineIgnoreCase_ThenHonored() =>
        // §11.6: inline options are part of the pattern and are honored.
        Assert.True(Matches("i21", null, "(?i)^I[0-9]{2}$"));

    [Fact]
    public void Discretize_WhenCurrentCultureIsDiscriminating_ThenMatchingIsCultureInvariant()
    {
        // The Turkish dotless-i is the classic discriminator: under tr-TR a culture-sensitive
        // engine would fold "I"/"i" differently. RegexOptions.CultureInvariant pins the behaviour
        // to be identical regardless of the ambient culture (P-11) — asserted by comparing the
        // SAME matches under an invariant and a Turkish current culture.
        var original = CultureInfo.CurrentCulture;
        try
        {
            CultureInfo.CurrentCulture = CultureInfo.InvariantCulture;
            var invariantUpper = Matches("I21", null, "(?i)^i[0-9]{2}$");
            var invariantLower = Matches("i21", null, "(?i)^I[0-9]{2}$");

            CultureInfo.CurrentCulture = CultureInfo.GetCultureInfo("tr-TR");
            Assert.Equal(invariantUpper, Matches("I21", null, "(?i)^i[0-9]{2}$"));
            Assert.Equal(invariantLower, Matches("i21", null, "(?i)^I[0-9]{2}$"));

            // And concretely: invariant case folding maps both ways.
            Assert.True(invariantUpper);
            Assert.True(invariantLower);
        }
        finally
        {
            CultureInfo.CurrentCulture = original;
        }
    }

    // --- Combined matchers ---------------------------------------------------

    [Theory]
    [InlineData("Bachelors", true)]  // explicit value
    [InlineData("I21", true)]        // pattern
    [InlineData("Masters", false)]   // neither
    public void Discretize_WhenValuesAndPattern_ThenOredWithinTheGroup(string value, bool expected) =>
        // §11.6: a value matches if it is in `values` OR matches `pattern`.
        Assert.Equal(expected, Matches(value, ["Bachelors"], "^I[0-9]{2}$"));

    [Fact]
    public void Create_WhenPatternCompiled_ThenTheMatcherCarriesAnExplicitInfiniteTimeout()
    {
        // §11.6/D-090/P-7: matching must not depend on host configuration. The Regex overloads that
        // omit a timeout inherit the ambient REGEX_DEFAULT_MATCH_TIMEOUT, so on a host that sets one
        // a catastrophically-backtracking pattern would throw RegexMatchTimeoutException out of
        // Discretize — the same spec over the same input completing on one machine and failing on
        // another, and failing on the EXCEPTION channel mid-calibrate/emit rather than the
        // diagnostic one (P-14). Passing InfiniteMatchTimeout explicitly is what forecloses that.
        //
        // Reflection because the compiled matcher is deliberately private (it is not public
        // surface). Scope, stated honestly: on a host with no ambient default configured the
        // omitting overload also yields an infinite timeout, so this assertion bites exactly on the
        // hosts where the bug would — plus on any explicit finite timeout, anywhere. A fully
        // discriminating regression needs a child process that configures a finite default before
        // Regex's static initializer runs; that is not safely reachable from inside this assembly
        // (the test host itself uses Regex), so it is deliberately not attempted here.
        var group = ValueGroup.Create("G", null, "^(a+)+$");
        var field = typeof(ValueGroup).GetField("_regex", BindingFlags.Instance | BindingFlags.NonPublic);
        var regex = Assert.IsType<Regex>(field!.GetValue(group));

        Assert.Equal(Regex.InfiniteMatchTimeout, regex.MatchTimeout);
        Assert.Equal(RegexOptions.CultureInvariant, regex.Options);
    }

    // --- Mutation isolation (D-098) ------------------------------------------

    [Fact]
    public void Create_WhenCallerMutatesItsValuesListAfterwards_ThenTheGroupIsUnaffected()
    {
        var authored = new List<string> { "a" };
        var group = ValueGroup.Create("G", authored, null);

        authored.Add("b");
        authored[0] = "z";

        Assert.Equal(["a"], group.Values);
        Assert.True(Matches("a", ["a"], null));
    }

    [Fact]
    public void Create_WhenCallerMutatesAListItWouldHaveSlippedAnEmptyValueInto_ThenTheSnapshotGateHeld()
    {
        // The snapshot is taken BEFORE validation, so a caller cannot pass a valid list, have it
        // accepted, and then mutate an empty value into the group's matcher.
        var authored = new List<string> { "a" };
        var group = ValueGroup.Create("G", authored, null);

        authored[0] = string.Empty;

        Assert.Equal(["a"], group.Values);
    }

    [Fact]
    public void Values_WhenAuthored_ThenNotCastableToAMutableCollection()
    {
        // Recursive immutability (D-098): no public IReadOnlyList may be cast back to its
        // backing array/list and mutated.
        var values = ValueGroup.Create("G", ["a", "b"], null).Values;

        Assert.NotNull(values);
        Assert.IsNotType<string[]>(values);
        Assert.IsNotType<List<string>>(values);
        Assert.IsType<ImmutableArray<string>>(values);
    }
}
